databases:
- name: rails_realtime_chat
  databaseName: rails_realtime_chat
  user: rails_realtime_chat_user

services:
- type: pserv
  name: redis
  env: docker
  disk:
    name: data
    mountPath: /var/lib/redis
    sizeGB: 1
- type: web
  name: rails-realtime-chat
  env: ruby
  buildCommand: "./bin/render-build.sh"
  startCommand: "bundle exec puma -C config/puma.rb"
  envVars:
    - key: DATABASE_URL
      fromDatabase:
        name: rails_realtime_chat
        property: connectionString
    - key: REDIS_HOSTPORT
      fromService:
        name: redis
        type: pserv
        property: hostport
    - key: SECRET_KEY_BASE
      sync: false
